### ISSUE TITLE
how to get the traindata?

### ISSUE THREAD

**Issue by xjtlbc** [foranonymous123/CNNforFaultInterpretation#2]
Can you tell me how to generate training data,thx！

**Comment by foranonymous123** [comment]
Hi @xjtlbc 
Thank you for your interest in this project. Are you also using SEGY file? In this project, we convert SEGY file to Numpy array, which can be seen as a large cube shape matrix (dimensional order can be easily changed as requested). This process we use the readSGY.ipynb file. For labels, we use Petrel software (a software geological fault interpreter often used) to virtualise the labels and save screenshots of each intersection. Details of this are shown in the "petrel workflow instruction.pdf". Screenshots are then processed to numpy array. 

I hope this makes sense to you.
