### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by RockMan1966** [foranonymous123/CNNforFaultInterpretation#8]
感谢小姐姐这么精彩的工作，我想问一下我应该如何获取数据集呢，我想将图片的大小转换成128*128的，我应该如何操作呢

**Comment by anyuzoey** [comment]
Not sure if you still have this question. You can use this code (https://github.com/anyuzoey/CNNforFaultInterpretation/blob/master/generatePatchipyTrainValTest.ipynb). Just change these lines: splitsize = 96 // this line control the split size.
stepsize = 48 // this line is optional
